name: Build Website

# We don't want pushes (or PRs) to gh-pages to kick anything off
on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+.x'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:

jobs:
  Build:
    name: Build with Sphinx
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: python -m pip install -r ci/build_requirements.txt

    - name: Build docs
      run: |
        pushd site
        make html linkcheck
        popd

    - name: Upload docs as artifact
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/upload-artifact@v2
      with:
        name: build-docs
        path: docs/build/html

    - name: Upload to GitHub Pages
      if: ${{ github.event_name != 'pull_request' }}
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        exclude_assets: '.buildinfo,_static/jquery-*.js,_static/underscore-*.js'
        keep_files: false
        full_commit_message: Deploy to GitHub Pages
